export const PART_DESCRIPTIONS = {
  "A-1IBM65819PXGCAT": "Copper Cactus Ball Marker",
  "A-1IBM65820PXG-DT": "2023 Darkness Dog Tag Ball Marker",
  "A-ALIGNSTICKS-WHT": "PXG Player Alignment Sticks - White",
  "A-DARKNESS-COASTER": "PXG Darkness Coaster",
  "A-ICU55715PXG-ALS": "PXG Deluxe Alignment Stick Cover",
  "A-IHC62918PXG-COP": "PXG Magnetic Ball Marker & Cap Clip - Rose Gold",
  "A-IHC62920PXG-BLK": "PXG Magnetic Ball Marker & Cap Clip - Black",
  "A-JT-4697": "Darkness Alignment Stick Cover - Black",
  "A-Q23192-ASM-2": "Chrome Logo Ball Marker",
  "A-Q25240-ASM": "Milled Starburst Ball Marker",
  "A-Q25645-ASM-1": "2025 Stars & Stripes Ball Marker",
  "A-Q25645-ASM-2": "2026 Stars & Stripes Ball Marker",
  "A-Q26442-ASM-2": "Lightning Ball Marker",
  "A-SHAFT-ADAPTER-DRIV": "Driver Shaft Adapter RH",
  "A-SHAFT-ADAPTER-HYB": "Hybrid Shaft Adapter RH",
  "A-SHAFT-ADPTR-DRIVLH": "Driver Shaft Adapter LH",
  "A-SHAFT-ADPTR-HYBLH": "Hybrid Shaft Adapter LH",
  "A-SHAFT-CTR-PC": "Shaft Centering Pieces",
  "A-SSWEIGHT-25G": "SuperStroke 25G Weight",
  "A-SSWEIGHT-50G": "SuperStroke 50G Weight",
  "A-TITANSLOPE-PXG": "PXG Titan Rangefinder Slope Edition",
  "A-TORQUETOOL": "TorqueTool-Woods/Hybrids",
  "A-TORQUETOOL-GEN4IR": "T20 Tamper Proof Torque Wrench (GEN4 Irons)",
  "A-UAC17-FM": "PXG Wedge Brush - Black",
  "A-UAC18-FM": "PXG Wedge Brush - Chrome",
  "A-UAC28-FM": "PXG Milled Divot Tool (Weighted)",
  "A-UAC29-FM": "PXG (DRKNSS) Divot Tool",
  "A-WEIGHTKIT-6PC": "Putter Full Weight Kit (6 Weights)",
  "A-WEIGHTKIT-DRIVER": "Metal Wood Full Weight Kit",
  "A-ZNP53374-1": "Darkness Leather Wrapped Divot Tool",
  "B-PG-081-BLK": "2023 PXG Deluxe Cart Bag - Black",
  "B-PG-172-26CO-OG": "Xtreme Carry Stand Bag - Fairway Camo - Olive Green",
  "B-PG-172-BGRY": "Xtreme Carry Stand Bag - Black",
  "B-PG-172-BLACK": "Xtreme Carry Stand Bag - Freedom - Black",
  "B-PG-172-DB": "Deluxe Carry Stand Bag - Black",
  "B-PG-172-DW": "Deluxe Carry Stand Bag - White",
  "B-PG-172-GREEN": "Xtreme Carry Stand Bag - Freedom - Green",
  "B-PG-172-GREY": "Xtreme Carry Stand Bag - Freedom - Grey",
  "B-PG-172-WBLK": "Xtreme Carry Stand Bag - White",
  "B-PG-172-WHTBLK": "Deluxe Carry Stand Bag - White/Black",
  "B-PG-172-XGB": "Xtreme Carry Stand Bag - Green/Black",
  "B-PG-172PU-26SS": "2026 Stars & Stripes Carry Stand Bag",
  "B-PG-173-14-XGB": "Xtreme Hybrid Stand Bag - 14 Way Top - Green/Black",
  "B-PG-173-BGRY": "Xtreme Hybrid Stand Bag - Black",
  "B-PG-173-BO": "Deluxe Hybrid Stand Bag - Black",
  "B-PG-173-NVYWHT": "Xtreme Hybrid Stand Bag - Navy/White",
  "B-PG-173-WBLK": "Xtreme Hybrid Stand Bag - White",
  "B-PG-173-WHTBLK": "Deluxe Hybrid Stand Bag - White/Black",
  "B-PG-173-WO": "Deluxe Hybrid Stand Bag - White",
  "B-PG-173-XGB": "Xtreme Hybrid Stand Bag - Green/Black",
  "B-PG-244": "Xtreme Cart Bag - White",
  "B-PG-245-BLK": "Deluxe Cart Bag B2 - Black",
  "B-PG-245-WHT": "Deluxe Cart Bag B2 - White",
  "B-PG-246-POLY": "Minimalist Carry Stand Bag - Black",
  "B-PG-286": "NextGen Den Caddy - Black/White",
  "B-TC-041": "Deluxe Golf Bag Travel Cover - Black",
  "B-UGB1-EP": "2020 Tour Bag- Black/White",
  "B-UGB14-FM": "PXG Sunday Stand Bag - Black/White",
  "G-GP-CP2MID-PRO": "Golf Pride CP2 Pro- Midsize",
  "G-GP-CP2MID-W": "Golf Pride CP2 Wrap- Midsize",
  "G-GP-CP2PRO-STD": "Golf Pride CP2 Pro- Standard",
  "G-GP-CP2WRAP-STD": "Golf Pride CP2 Wrap- Standard",
  "G-GP-MC-MID-WHT": "Golf Pride MultiCompound White- Midsize",
  "G-GP-MC-STD-WHITE": "Golf Pride MultiCompound White- Standard",
  "G-GP-MCPLUS4-MID-GRY": "Golf Pride MultiCompound +4 Grey- Midsize",
  "G-GP-MCPLUS4-STD-GRY": "Golf Pride MultiCompound +4 Grey- Standard",
  "G-GP-TOURV-58-UND": "Golf Pride Tour Velvet 58- Undersized",
  "G-GP-TOURV-60-STD": "Golf Pride Tour Velvet 60- Standard",
  "G-GP-TOURV-CORD": "Golf Pride Tour Velvet Cord",
  "G-GP-TOURV-MID": "Golf Pride Tour Velvet- Midsize",
  "G-GP-TOURW-58R-BLK": "Golf Pride Tour Wrap 58R Black- Standard",
  "G-GP-TOURW-58R-WHITE": "Golf Pride Tour Wrap 60R White- Standard",
  "G-GP-TOURW-60R-MBLK": "Golf Pride Tour Wrap 60R Black- Midsize",
  "G-GP-TOURW-60R-MWHT": "Golf Pride Tour Wrap 60R White- Midsize",
  "G-GP-TOURZ-MID-CORD": "Golf Pride Z-Cord- Midsize",
  "G-GP-TOURZ-STD-CORD": "Golf Pride Z-Cord- Standard",
  "G-GP-TV360-BLK-MID": "Golf Pride Tour Velvet 360 Black - Midsize",
  "G-GP-TV360-BLK-OVR": "Golf Pride Tour Velvet 360 Black - Jumbo",
  "G-GP-TV360-BLK-STD": "Golf Pride Tour Velvet 360 Black - Standard",
  "G-GP-TV360-BLK-UND": "Golf Pride Tour Velvet 360 Black - Undersize",
  "G-LAMK-PXG-SKINNY": "Lamkin PXG Sink Fit Skinny",
  "G-LAMK-Z5-MID-BLK": "PXG Z5 Black- Midsize",
  "G-LAMK-Z5-OVR-BLK": "PXG Z5 Black- Oversize",
  "G-LAMK-Z5-STD-BLK": "PXG Z5 Black- Standard",
  "G-PXG-PG-PST-I-BLK": "PXG Pistol I Putter Grip - Black",
  "G-PXG-PG-PST-II-BLK": "PXG Pistol II Putter Grip - Black",
  "G-PXG-PG-PST-III-BLK": "PXG Pistol III Putter Grip - Black",
  "G-PXG-PG-SLT-1.5-L-BLK": "PXG Slant 1.5 L Putter Grip - Black",
  "G-PXG-PG-SLT-1.5-R-BLK": "PXG Slant 1.5 R Putter Grip - Black",
  "G-PXG-PG-SLTPST-MID-L-BLK": "PXG Slant Pistol Mid L Putter Grip - Black",
  "G-PXG-PG-SLTPST-MID-R-BLK": "PXG Slant Pistol Mid R Putter Grip - Black",
  "G-PXG-PG-SLTPST-STD-L-BLK": "PXG Slant Pistol L Putter Grip - Black",
  "G-PXG-PG-SLTPST-STD-R-BLK": "PXG Slant Pistol R Putter Grip - Black",
  "G-PXG-PG-STR-I-BLK": "PXG Straight I Putter Grip - Black",
  "G-PXG-PG-STR-II-BLK": "PXG Straight II Putter Grip - Black",
  "G-PXG-PG-STR-III-BLK": "PXG Straight III Putter Grip - Black",
  "G-PXG-PG-STR-XL-BLK": "PXG Straight XL Putter Grip - Black",
  "G-SS-17PXG-FLATSO2.0": "SuperStroke PXG Flatso 2.0- Black",
  "G-SS-17PXG-FLATSO3.0": "SuperStroke PXG Flatso 3.0- Black",
  "G-SS-2017PXG-FLATSO": "SuperStroke PXG Flatso 1.0- Black",
  "G-SS-2017PXG-MS2.0": "SuperStroke PXG Mid Slim 2.0- Black",
  "G-SS-2017PXG-MS2.0XL": "SuperStroke PXG Plus 2.0 XL- Black",
  "G-SS-2017PXG-MS3.0": "SuperStroke PXG Slim 3.0- Black",
  "G-SS-2017PXG-MS5.0": "SuperStroke PXG Fatso 5.0- Black",
  "G-SS-2017PXG-PISTOL": "SuperStroke PXG Pistol 1.0- Black",
  "G-SS-CRSLN2.0-JUM-GRY": "SuperStroke Crossline 2.0 Grey - Jumbo",
  "G-SS-CRSLN2.0-MID-GRY": "SuperStroke Crossline 2.0 Grey - Midsize",
  "G-SS-CRSLN2.0-STD-GRY": "SuperStroke Crossline 2.0 Grey - Standard",
  "G-SS-REVLCMFT-JUM-WHT": "SuperStroke REVL Comfort White - Jumbo",
  "G-SS-REVLCMFT-MID-WHT": "SuperStroke REVL Comfort White - Midsize",
  "G-SS-REVLCMFT-STD-WHT": "SuperStroke REVL Comfort White - Standard",
  "G-SS-REVLEL4X-MID-BLK": "SuperStroke REVL Element 4X Black - Midsize",
  "G-SS-REVLEL4X-STD-BLK": "SuperStroke REVL Element 4X Black - Standard",
  "G-TT-ICON-PXG-MID-BLK": "PXG ICON Black - Midsize",
  "G-TT-ICON-PXG-OVR-BLK": "PXG ICON Black - Oversize",
  "G-TT-ICON-PXG-STD-BLK": "PXG ICON Black - Standard",
  "G-TT-ICON-PXG-UND-BLK": "PXG ICON Black - Undersize",
  "G-WINN-DRI-MID-GR": "Winn Dri-Tac Dark Gray- Midsize",
  "G-WINN-DRI-OVR-GR": "Winn Dri-Tac Dark Gray- Oversized",
  "G-WINN-DRI-STD-GR": "Winn Dri-Tac Dark Gray- Standard",
  "G-WINN-DRI-UNDR-GR": "Winn Dri-Tac Dark Gray- Undersized",
  "G-WINN-DRIWRP-MID-GR": "Winn Dri Tac WRAP Dark Gray- Midsize",
  "G-WINN-DRIWRP-OVR-GR": "Winn Dri Tac WRAP Dark Gray- Oversized",
  "G-WINN-DRIWRP-STD-GR": "Winn Dri Tac WRAP Dark Gray- Standard",
  "G-WINN-EXCEL-OVR-BLK": "Winn Excel Wrap Black - Oversized",
  "G4-652011019LHL-BLK": "Men's LH Players Glove - Black L",
  "G4-652011019LHLC-BLK": "Men's LH Players Glove - Cadet Black L",
  "G4-652011019LHLW-BLK": "Women's LH Players Glove- Black L",
  "G4-652011019LHM-BLK": "Men's LH Players Glove - Black M",
  "G4-652011019LHMC-BLK": "Men's LH Players Glove - Cadet Black M",
  "G4-652011019LHML-BLK": "Men's LH Players Glove - Black ML",
  "G4-652011019LHMLC-BLK": "Men's LH Players Glove - Cadet Black ML",
  "G4-652011019LHMW-BLK": "Women's LH Players Glove- Black M",
  "G4-652011019LHS-BLK": "Men's LH Players Glove - Black S",
  "G4-652011019LHSC-BLK": "Men's LH Players Glove - Cadet Black S",
  "G4-652011019LHSW-BLK": "Women's LH Players Glove- Black S",
  "G4-652011019LHXL-BLK": "Men's LH Players Glove - Black XL",
  "G4-652011019LHXLC-BLK": "Men's LH Players Glove - Cadet Black XL",
  "G4-652011019RHL-BLK": "Men's RH Players Glove - Black L",
  "G4-652011019RHLC-BLK": "Men's RH Players Glove - Cadet Black L",
  "G4-652011019RHM-BLK": "Men's RH Players Glove - Black M",
  "G4-652011019RHMC-BLK": "Men's RH Players Glove - Cadet Black M",
  "G4-652011019RHML-BLK": "Men's RH Players Glove - Black ML",
  "G4-652011019RHMLC-BLK": "Men's RH Players Glove - Cadet Black ML",
  "G4-652011019RHS-BLK": "Men's RH Players Glove - Black S",
  "G4-652011019RHSC-BLK": "Men's RH Players Glove - Cadet Black S",
  "G4-652011019RHXL-BLK": "Men's RH Players Glove - Black XL",
  "G4-652011019RHXLC-BLK": "Men's RH Players Glove - Cadet Black XL",
  "G4-652011019RHXXL-BLK": "Men's RH Players Glove - Black XXL",
  "G4-652021019LHL-WHT": "Men's LH Players Glove - White L",
  "G4-652021019LHLC-WHT": "Men's LH Players Glove - Cadet White L",
  "G4-652021019LHLW-WHT": "Women's LH Players Glove- White L",
  "G4-652021019LHM-WHT": "Men's LH Players Glove - White M",
  "G4-652021019LHMC-WHT": "Men's LH Players Glove - Cadet White M",
  "G4-652021019LHML-WHT": "Men's LH Players Glove - White ML",
  "G4-652021019LHMLC-WHT": "Men's LH Players Glove - Cadet White ML",
  "G4-652021019LHMW-WHT": "Women's LH Players Glove- White M",
  "G4-652021019LHS-WHT": "Men's LH Players Glove - White S",
  "G4-652021019LHSC-WHT": "Men's LH Players Glove - Cadet White S",
  "G4-652021019LHSW-WHT": "Women's LH Players Glove- White S",
  "G4-652021019LHXL-WHT": "Men's LH Players Glove - White XL",
  "G4-652021019LHXLC-WHT": "Men's LH Players Glove - Cadet White XL",
  "G4-652021019LHXXL-WHT": "Men's LH Players Glove - White XXL",
  "G4-652021019RHL-WHT": "Men's RH Players Glove - White L",
  "G4-652021019RHLC-WHT": "Men's RH Players Glove - Cadet White L",
  "G4-652021019RHLW-WHT": "Women's RH Players Glove- White L",
  "G4-652021019RHM-WHT": "Men's RH Players Glove - White M",
  "G4-652021019RHMC-WHT": "Men's RH Players Glove - Cadet White M",
  "G4-652021019RHML-WHT": "Men's RH Players Glove - White ML",
  "G4-652021019RHMLC-WHT": "Men's RH Players Glove - Cadet White ML",
  "G4-652021019RHMW-WHT": "Women's RH Players Glove- White M",
  "G4-652021019RHS-WHT": "Men's RH Players Glove - White S",
  "G4-652021019RHSC-WHT": "Men's RH Players Glove - Cadet White S",
  "G4-652021019RHSW-WHT": "Women's RH Players Glove- White S",
  "G4-652021019RHXL-WHT": "Men's RH Players Glove - White XL",
  "G4-652021019RHXLC-WHT": "Men's RH Players Glove - Cadet White XL",
  "G4-652021019RHXXL-WHT": "Men's RH Players Glove - White XXL",
  "GB-DOZ-XTTR-WHT": "Xtreme Tour Golf Ball - White - Dozen",
  "GB-DOZ-XTTR-WHT-AF": "Xtreme Tour Golf Ball - White - Air Force - Dozen",
  "GB-DOZ-XTTR-WHT-ARMY": "Xtreme Tour Golf Ball - White - Army - Dozen",
  "GB-DOZ-XTTR-WHT-NAVY": "Xtreme Tour Golf Ball - White - Navy - Dozen",
  "GB-DOZ-XTTR-WHT-USMC": "Xtreme Tour Golf Ball - White - USMC - Dozen",
  "GB-DOZ-XTTR-YEL": "Xtreme Tour Golf Ball - Yellow - Dozen",
  "GB-DOZ-XTTRX-WHT": "Xtreme Tour X Golf Ball - White - Dozen",
  "GB-DOZ-XTTRX-WHT-AF": "Xtreme Tour X Golf Ball - White - Air Force - Dozen",
  "GB-DOZ-XTTRX-WHT-USMC": "Xtreme Tour X Golf Ball - White - USMC - Dozen",
  "H-22PXG000013-BLK": "Tall Visor - Black",
  "H-22PXG000013-WHT": "Tall Visor - White",
  "H-22PXG000014-BLK": "Sport Visor - Black",
  "H-22PXG000014-WHT": "Sport Visor - White",
  "H-23PXG0000124-2-BG-OSFM":
    "Dog Tag 6-Panel Snapback Cap - Black/Grey Logo - One Size",
  "H-23PXG0000124-2-GB-OSFM":
    "Dog Tag 6-Panel Snapback Cap - Grey/Black Logo - One Size",
  "H-23PXG000078-1-L-XL": "Tour Bush Hat - White - L/XL",
  "H-23PXG000094-1-OSFM-BLK": "Faceted Front Trucker Cap - Black - One Size",
  "H-23PXG000094-1-OSFM-WHT": "Faceted Front Trucker Cap - White - One Size",
  "H-23PXG000101-BW-OSFM":
    "Men's 6-Panel High Crown Snapback Cap - Black/White Logo - One Size",
  "H-23PXG000101-NW-OSFM":
    "Men's 6-Panel High Crown Snapback Cap - Navy/White Logo - One Size",
  "H-23PXG000101-WB-OSFM":
    "Men's 6-Panel High Crown Snapback Cap - White/Black Logo - One Size",
  "H-23PXG000123-BG-OSFM":
    "Men's Dog Tag 6-Panel High Crown Snapback Cap - Black/Grey Logo - One Size",
  "H-23PXG000123-BW-OSFM":
    "Men's Dog Tag 6-Panel High Crown Snapback Cap - Black/White Logo - One Size",
  "H-23PXG000123-GB-OSFM":
    "Men's Dog Tag 6-Panel High Crown Snapback Cap - Grey/Black Logo - One Size",
  "H-23PXG000125-BG-OSFM":
    "Men's Dog Tag 5-Panel Snapback Cap - Black/Grey Logo - One Size",
  "H-23PXG000125-BW-OSFM":
    "Men's Dog Tag 5-Panel Snapback Cap - Black/White Logo - One Size",
  "H-23PXG000125-WG-OSFM":
    "Men's Dog Tag 5-Panel Snapback Cap - White/Grey Logo - One Size",
  "H-23PXG000166-BLK-OSFM": "Stretch Snapback Hat - Black - One Size",
  "H-23PXG000166-WHT-OSFM": "Stretch Snapback Hat - White - One Size",
  "H-23PXG000167-BW-OSFM":
    "Scottsdale Trucker Snapback Hat - Black/White Logo - One Size",
  "H-23PXG000167-WB-OSFM":
    "Scottsdale Trucker Snapback Hat - White/Blue Logo - One Size",
  "H-23PXG000167-WW-OSFM":
    "Scottsdale Trucker Snapback Hat - White/White Logo - One Size",
  "H-23PXG000168-BLK-OSFM": "Stretch Patch Snapback Hat - Black - One Size",
  "H-23PXG000168-GRY-OSFM": "Stretch Patch Snapback Hat - Grey - One Size",
  "H-23PXG000168-WHT-OSFM": "Stretch Patch Snapback Hat - White - One Size",
  "H-24PXG000203-2-BLK-OSFM":
    "Women's Metallic Minimalist - Unstructured Hat - Black - One Size",
  "H-24PXG000214-1-BLK-OSFM":
    "Camper Flat Bill Snapback Cap - Black - One Size",
  "H-24PXG000214-1-WHT-OSFM":
    "Camper Flat Bill Snapback Cap - White - One Size",
  "H-24PXG000218-1-OSFM":
    "6 Panel Structured Low Crown Snapback - Warm Sand - One Size",
  "H-24PXG000219-OSFM":
    "Women's Metallic Minimalist - Unstructured Hat - Pink - One Size",
  "H-24PXG000229-OSFM": "US Navy Structured Hat Snapback - One Size",
  "H-24PXG000235-GB-OSFM":
    "Dog Tag 6-Panel Low Crown Snapback Cap - Grey/Black - One Size",
  "H-24PXG000235-WG-OSFM":
    "Dog Tag 6-Panel Low Crown Snapback Cap - White/Grey - One Size",
  "H-24PXG000239-OSFM":
    "Women's Metallic Minimalist - Unstructured Hat - Light Blue - One Size",
  "H-25PXG000364-BB-OSFM": "Minimalist Trucker Mesh Cap - Black/Black",
  "H-25PXG000364-WW-OSFM": "Minimalist Trucker Mesh Cap - White/White",
  "H-25PXG000385-OSFM": "Digital Camo Hat - Desert Tan",
  "H-25PXG000386-GB-OSFM": "Minimalist Trucker Mesh Cap - Gray/Black",
  "H-25PXG000386-WB-OSFM": "Minimalist Trucker Mesh Cap - White/Black",
  "H-25PXG000386-WG-OSFM": "Minimalist Trucker Mesh Cap - White/Green",
  "H-25PXG000386-WN-OSFM": "Minimalist Trucker Mesh Cap - White/Navy",
  "H-25PXG000387-GW-OSFM": "Minimalist Trucker Mesh Cap - Green/White",
  "H-25PXG000387-NW-OSFM": "Minimalist Trucker Mesh Cap - Navy/White",
  "H-25PXG000394-BW-OSFM": "Minimalist Rope Hat - Black/White",
  "H-25PXG000394-GB-OSFM": "Minimalist Rope Hat - Grey/Black",
  "H-25PXG000394-WB-OSFM": "Minimalist Rope Hat - White/Black",
  "H-25PXG000396-TH-OSFM": "Minimalist Rope Hat - Thyme",
  "H-25PXG000396-VW-OSFM": "Minimalist Rope Hat - Vintage White",
  "H-USMC-ADJ": "PXG USMC Unstructured Hat - Adjustable",
  "HC-1304-RLMALSB": "Repeat Logo Mallet Putter Cover - S Bend",
  "HC-1314-LTNDR": "Lightning Driver Headcover",
  "HC-1322-WCDR": "Wildcat Driver Headcover",
  "HC-1342-SWDR": "Secret Weapon Driver Headcover - Black",
  "HC-1349-RLBLD": "Repeat Logo Blade Putter Cover",
  "HC-1352-WCFW5": "Wildcat 5 Wood Headcover",
  "HC-1353-WCHY6": "Wildcat 6 Hybrid Headcover",
  "HC-1356-25SSBLD": "2025 Stars & Stripes Blade Headcover",
  "HC-1357-LTNFW": "Lightning Fairway Headcover",
  "HC-1358-LTNHY": "Lightning Hybrid Headcover",
  "HC-1381-RLMALCS": "Repeat Logo Mallet Putter Cover - Center Shafted",
  "HC-1416-26SSBLD": "2026 Stars & Stripes Blade Headcover",
  "HC-1417-SW2DR": "Secret Weapon Flame Driver Headcover",
  "HC-GEN6-PATCH-11": "PXG GEN6 Headcover Patch - 11",
  "HC-GEN6-PATCH-17": "PXG GEN6 Headcover Patch - 17",
  "HC-GEN6-PATCH-19": "PXG GEN6 Headcover Patch - 19",
  "HC-GEN6-PATCH-2": "PXG GEN6 Headcover Patch - 2",
  "HC-GEN6-PATCH-22": "PXG GEN6 Headcover Patch - 22",
  "HC-GEN6-PATCH-25": "PXG GEN6 Headcover Patch - 25",
  "HC-GEN6-PATCH-28": "PXG GEN6 Headcover Patch - 28",
  "HC-GEN6-PATCH-3": "PXG GEN6 Headcover Patch - 3",
  "HC-GEN6-PATCH-31": "PXG GEN6 Headcover Patch - 31",
  "HC-GEN6-PATCH-4": "PXG GEN6 Headcover Patch - 4",
  "HC-GEN6-PATCH-5": "PXG GEN6 Headcover Patch - 5",
  "HC-GEN6-PATCH-7": "PXG GEN6 Headcover Patch - 7",
  "HC-GEN6-PATCH-9": "PXG GEN6 Headcover Patch - 9",
  "HC-ICU65199PXG-APC": "Battle Ready II Square Mallet Putter Cover",
  "HC-ICU65199PXG-BLD": "Battle Ready II Blade Putter Cover",
  "HC-ICU65199PXG-CM": "Battle Ready II Center Mallet Putter Cover",
  "HC-ICU65199PXG-HLF": "Battle Ready II Half Mallet Putter Cover",
  "HC-ICU65199PXG-MAL": "Battle Ready II Mallet Putter Cover",
  "HC-ICU66579GEN7-DR": "PXG Black Ops Driver Quickstick Headcover",
  "HC-ICU66579GEN7-FW": "PXG Black Ops Fairway Quickstick Headcover",
  "HC-ICU66579GEN7-HY": "PXG Black Ops Hybrid Quickstick Headcover",
  "HC-JT-1053-KIT": "PXG 2022 Iron Cover Kit",
  "HC-JT-4623": "Tour Series Blade Headcover - Black",
  "HC-JT-4831": "Tour Series Wide Blade Headcover - Black",
  "HC-LTNHCP11": "Lightning Headcover Patch - 11",
  "HC-LTNHCP17": "Lightning Headcover Patch - 17",
  "HC-LTNHCP19": "Lightning Headcover Patch - 19",
  "HC-LTNHCP22": "Lightning Headcover Patch - 22",
  "HC-LTNHCP25": "Lightning Headcover Patch - 25",
  "HC-LTNHCP28": "Lightning Headcover Patch - 28",
  "HC-LTNHCP3": "Lightning Headcover Patch - 3",
  "HC-LTNHCP31": "Lightning Headcover Patch - 31",
  "HC-LTNHCP34": "Lightning Headcover Patch - 34",
  "HC-LTNHCP4": "Lightning Headcover Patch - 4",
  "HC-LTNHCP5": "Lightning Headcover Patch - 5",
  "HC-LTNHCP7": "Lightning Headcover Patch - 7",
  "HC-LTNHCP9": "Lightning Headcover Patch - 9",
  "HC-LTNHCPX": "Lightning Headcover Patch - X",
  "HC2-2020-MALLET-BLK": "PXG 2020 Mallet Headcover",
  "HC2-2020-WIDEBLADE-BLK": "PXG 2020 Wide Blade Headcover",
  "T-DISCWEIGHT-10G": "10g Disc Weight",
  "T-DISCWEIGHT-12.5G": "12.5g Disc Weight",
  "T-DISCWEIGHT-15G": "15g Disc Weight",
  "T-DISCWEIGHT-17.5G": "17.5g Disc Weight",
  "T-DISCWEIGHT-2.5G-TI": "2.5g Ti Disc Weight",
  "T-DISCWEIGHT-20G": "20g Disc Weight",
  "T-DISCWEIGHT-5G": "5g Disc Weight",
  "T-DISCWEIGHT-7.5G": "7.5g Disc Weight",
  "T-FERRULE-IRON-355": ".355 ID Iron Ferrule (MF9017C-15.24*14.2)",
  "T-FERRULE-IRON-360": ".360 ID Iron Ferrule (MF914C-15.24*14.2)",
  "T-FERRULE-PUTTER": "Putter Ferrule (F80C-2.54*9.65)",
  "T-FERRULE-WEDGE-355": ".355 ID Wedge Ferrule (MF9017C-15.9*14.7)",
  "T-FERRULE-WEDGE-360": ".360 ID Wedge Ferrule (MF914C-15.9*14.7)",
  "T-G4IRONWGHT-10.5G": "Iron Weight Black- 10.5g",
  "T-G4IRONWGHT-10G": "Iron Weight Black- 10g",
  "T-G4IRONWGHT-11.5G": "Iron Weight Black- 11.5g",
  "T-G4IRONWGHT-11G": "Iron Weight Black- 11g",
  "T-G4IRONWGHT-12.5G": "Iron Weight Black- 12.5g",
  "T-G4IRONWGHT-12G": "Iron Weight Black- 12g",
  "T-G4IRONWGHT-13.5G": "Iron Weight Black- 13.5g",
  "T-G4IRONWGHT-13G": "Iron Weight Black- 13g",
  "T-G4IRONWGHT-14.5G": "Iron Weight Black- 14.5g",
  "T-G4IRONWGHT-14G": "Iron Weight Black- 14g",
  "T-G4IRONWGHT-15.5G": "Iron Weight Black- 15.5g",
  "T-G4IRONWGHT-15G": "Iron Weight Black- 15g",
  "T-G4IRONWGHT-16.5G": "Iron Weight Black- 16.5g",
  "T-G4IRONWGHT-16G": "Iron Weight Black- 16g",
  "T-G4IRONWGHT-17.5G": "Iron Weight Black- 17.5g",
  "T-G4IRONWGHT-17G": "Iron Weight Black- 17g",
  "T-G4IRONWGHT-18G": "Iron Weight Black- 18g",
  "T-G4IRONWGHT-2.5G": "Iron Weight Black- 2.5g",
  "T-G4IRONWGHT-3.5G": "Iron Weight Black- 3.5g",
  "T-G4IRONWGHT-3G": "Iron Weight Black- 3g",
  "T-G4IRONWGHT-4.5G": "Iron Weight Black- 4.5g",
  "T-G4IRONWGHT-4G": "Iron Weight Black- 4g",
  "T-G4IRONWGHT-5.5G": "Iron Weight Black- 5.5g",
  "T-G4IRONWGHT-5G": "Iron Weight Black- 5g",
  "T-G4IRONWGHT-6.5G": "Iron Weight Black- 6.5g",
  "T-G4IRONWGHT-6G": "Iron Weight Black- 6g",
  "T-G4IRONWGHT-7.5G": "Iron Weight Black- 7.5g",
  "T-G4IRONWGHT-7G": "Iron Weight Black- 7g",
  "T-G4IRONWGHT-8.5G": "Iron Weight Black- 8.5g",
  "T-G4IRONWGHT-8G": "Iron Weight Black- 8g",
  "T-G4IRONWGHT-9.5G": "Iron Weight Black- 9.5g",
  "T-G4IRONWGHT-9G": "Iron Weight Black- 9g",
  "T-G4IRONWGHT-SIL-10.5G": "Iron Weight Silver- 10.5g",
  "T-G4IRONWGHT-SIL-10G": "Iron Weight Silver- 10g",
  "T-G4IRONWGHT-SIL-11.5G": "Iron Weight Silver- 11.5g",
  "T-G4IRONWGHT-SIL-11G": "Iron Weight Silver- 11g",
  "T-G4IRONWGHT-SIL-12.5G": "Iron Weight Silver- 12.5g",
  "T-G4IRONWGHT-SIL-12G": "Iron Weight Silver- 12g",
  "T-G4IRONWGHT-SIL-13.5G": "Iron Weight Silver- 13.5g",
  "T-G4IRONWGHT-SIL-13G": "Iron Weight Silver- 13g",
  "T-G4IRONWGHT-SIL-14.5G": "Iron Weight Silver- 14.5g",
  "T-G4IRONWGHT-SIL-14G": "Iron Weight Silver- 14g",
  "T-G4IRONWGHT-SIL-15.5G": "Iron Weight Silver- 15.5g",
  "T-G4IRONWGHT-SIL-15G": "Iron Weight Silver- 15g",
  "T-G4IRONWGHT-SIL-16.5G": "Iron Weight Silver- 16.5g",
  "T-G4IRONWGHT-SIL-16G": "Iron Weight Silver- 16g",
  "T-G4IRONWGHT-SIL-17.5G": "Iron Weight Silver- 17.5g",
  "T-G4IRONWGHT-SIL-17G": "Iron Weight Silver- 17g",
  "T-G4IRONWGHT-SIL-18G": "Iron Weight Silver- 18g",
  "T-G4IRONWGHT-SIL-3.5G": "Iron Weight Silver- 3.5g",
  "T-G4IRONWGHT-SIL-3G": "Iron Weight Silver- 3g",
  "T-G4IRONWGHT-SIL-4.5G": "Iron Weight Silver- 4.5g",
  "T-G4IRONWGHT-SIL-4G": "Iron Weight Silver- 4g",
  "T-G4IRONWGHT-SIL-5.5G": "Iron Weight Silver- 5.5g",
  "T-G4IRONWGHT-SIL-5G": "Iron Weight Silver- 5g",
  "T-G4IRONWGHT-SIL-6.5G": "Iron Weight Silver- 6.5g",
  "T-G4IRONWGHT-SIL-6G": "Iron Weight Silver- 6g",
  "T-G4IRONWGHT-SIL-7.5G": "Iron Weight Silver- 7.5g",
  "T-G4IRONWGHT-SIL-7G": "Iron Weight Silver- 7g",
  "T-G4IRONWGHT-SIL-8.5G": "Iron Weight Silver- 8.5g",
  "T-G4IRONWGHT-SIL-8G": "Iron Weight Silver- 8g",
  "T-G4IRONWGHT-SIL-9.5G": "Iron Weight Silver- 9.5g",
  "T-G4IRONWGHT-SIL-9G": "Iron Weight Silver- 9g",
  "T-GEN8IRWGT-BLK-10G": "GEN8 Iron Weight - Black - 10g",
  "T-GEN8IRWGT-BLK-11G": "GEN8 Iron Weight - Black - 11g",
  "T-GEN8IRWGT-BLK-12G": "GEN8 Iron Weight - Black - 12g",
  "T-GEN8IRWGT-BLK-2G": "GEN8 Iron Weight - Black - 2g",
  "T-GEN8IRWGT-BLK-3G": "GEN8 Iron Weight - Black - 3g",
  "T-GEN8IRWGT-BLK-4G": "GEN8 Iron Weight - Black - 4g",
  "T-GEN8IRWGT-BLK-5G": "GEN8 Iron Weight - Black - 5g",
  "T-GEN8IRWGT-BLK-6G": "GEN8 Iron Weight - Black - 6g",
  "T-GEN8IRWGT-BLK-7G": "GEN8 Iron Weight - Black - 7g",
  "T-GEN8IRWGT-BLK-8G": "GEN8 Iron Weight - Black - 8g",
  "T-GEN8IRWGT-BLK-9G": "GEN8 Iron Weight - Black - 9g",
  "T-GEN8IRWGT-SIL-10G": "GEN8 Iron Weight - Silver - 10g",
  "T-GEN8IRWGT-SIL-11G": "GEN8 Iron Weight - Silver - 11g",
  "T-GEN8IRWGT-SIL-12G": "GEN8 Iron Weight - Silver - 12g",
  "T-GEN8IRWGT-SIL-2G": "GEN8 Iron Weight - Silver - 2g",
  "T-GEN8IRWGT-SIL-3G": "GEN8 Iron Weight - Silver - 3g",
  "T-GEN8IRWGT-SIL-4G": "GEN8 Iron Weight - Silver - 4g",
  "T-GEN8IRWGT-SIL-5G": "GEN8 Iron Weight - Silver - 5g",
  "T-GEN8IRWGT-SIL-6G": "GEN8 Iron Weight - Silver - 6g",
  "T-GEN8IRWGT-SIL-7G": "GEN8 Iron Weight - Silver - 7g",
  "T-GEN8IRWGT-SIL-8G": "GEN8 Iron Weight - Silver - 8g",
  "T-GEN8IRWGT-SIL-9G": "GEN8 Iron Weight - Silver - 9g",
  "T-IRON-FITTING-SLEEV": "Fitting Head Iron Shaft Sleeve",
  "T-TIPWEIGHT-1G": "Tip Weight- 1 gram",
  "T-TIPWEIGHT-2G": "Tip Weight- 2 gram",
  "T-TIPWEIGHT-3G": "Tip Weight- 3 gram",
  "T-TIPWEIGHT-4G": "Tip Weight- 4 gram",
  "T-TIPWEIGHT-5G": "Tip Weight- 5 gram",
  "T-TIPWEIGHT-6G": "Tip Weight- 6 gram",
  "T-TIPWEIGHT-7G": "Tip Weight- 7 gram",
  "T-TIPWEIGHT-8G": "Tip Weight- 8 gram",
  "B-PG-082-WHT": "2023 PXG Lightweight Cart Bag - White/Black",
  "B-PG-172": "2025 Stars & Stripes LW Carry Stand Bag",
  "B-PG-172-DKNSS": "Deluxe Carry Stand Bag - Darkness",
  "B-PG-172-NAVY": "Xtreme Carry Stand Bag - Freedom - Navy",
  "B-PG-172-TAN": "Xtreme Carry Stand Bag - Freedom - Tan",
  "B-PG-173": "2025 Stars & Stripes Hybrid Stand Bag",
  "B-PG-173-DKNSS": "Deluxe Hybrid Stand Bag - Darkness",
  "B-PG-245": "2025 Stars & Stripes Cart Bag",
  "B-UGB8-EP": "2020 Carry Stand Bag - Black",
  "B-UGB2-EP": "2020 Tour Bag- Black",
  "B-UGB13-EP-B": "Den Caddy- Black",
  "GB-DOZ-XTREME": "Xtreme Golf Ball - Dozen",
  "H-23PXG0000124-2-BW-OSFM":
    "Dog Tag 6-Panel Snapback Cap - Black/White Logo - One Size",
  "H-23PXG0000124-2-CG-OSFM":
    "Dog Tag 6-Panel Snapback Cap - White/Grey Logo - One Size",
  "H-23PXG0000124-2-WG-OSFM":
    "Dog Tag 6-Panel Snapback Cap - White/Grey Logo - One Size",
  "H-23PXG000078-1-S-M": "Tour Bush Hat - White - S/M",
  "H-23PXG000101-WG-OSFM":
    "Men's 6-Panel High Crown Snapback Cap - White/Grey Logo - One Size",
  "H-23PXG000123-WG-OSFM":
    "Men's Dog Tag 6-Panel High Crown Snapback Cap - White/Grey Logo - One Size",
  "H-23PXG000125-WN-OSFM":
    "Men's Dog Tag 5-Panel Snapback Cap - White/Navy Logo - One Size",
  "H-23PXG000125-GB-OSFM":
    "Men's Dog Tag 5-Panel Snapback Cap - Grey/Black Logo - One Size",
  "H-23PXG000125-NW-OSFM":
    "Men's Dog Tag 5-Panel Snapback Cap - Navy/White Logo - One Size",
  "H-23PXG000126-WN-OSFM": "Stretch Snapback Hat - White - One Size",
  "H-23PXG000167-GB-OSFM":
    "Scottsdale Trucker Snapback Hat - Grey/Black Logo - One Size",
  "H-23PXG000167-WHT-OSFM":
    "Scottsdale Trucker Snapback Hat - White - One Size",
  "H-23PXG000168-NVY-OSFM": "Stretch Patch Snapback Hat - Navy - One Size",
  "H-24PXG000203-2-WHT-OSFM":
    "Women's Metallic Minimalist - Unstructured Hat - White - One Size",
  "H-24PXG000235-BW-OSFM":
    "Dog Tag 6-Panel Low Crown Snapback - Black/White Logo - One Size",
  "H-24PXG000276-OSFM": "2025 Stars & Stripes Low Crown Cap - One Size",
  "H-24PXG000277-OSFM": "2025 Stars & Stripes Dog Tag Cap - One Size",
  "H-24PXG000278-OSFM": "2025 Stars & Stripes High Crown Cap - One Size",
  "H-25PXG000282-OSFM": "2025 Stars & Stripes Trucker Cap - One Size",
  "H-24PXG000282-OSFM": "2025 Stars & Stripes Trucker Cap - One Size",
  "H-25PXG000283-OSFM": "2025 Stars & Stripes Dog Tag Trucker - One Size",
  "A-NX10SLOPE-PXG": "PXG NX10 Rangefinder Slope Edition - White",
  "A-DUO-PXG": "PXG Golf Speaker - White",
} as const;
